### ISSUE TITLE
Getting selected values in the parent LWC

### ISSUE THREAD

**Issue by ChaimaaTaoui** [svierk/awesome-lwc-collection#64]
Hi, thank you for this component. I checked but couldn't find in the doc how to get the selected values (shown in the pill-container) in the parent/host lwc . 
Thanks .

**Comment by svierk** [comment]
Hi, I explained the component in one of my blog posts on Medium. This also describes how to access the currently selected values from a parent component: [How to Create the LWC Multi-Select Combobox that Salesforce is Still Missing](https://medium.com/javascript-in-plain-english/how-to-create-the-lwc-multi-select-combobox-that-salesforce-is-still-missing-c7bf3a2850dd)

**Comment by svierk** [comment]
Since I haven't heard back and the article already explains it, I will close this thread
