### ISSUE TITLE
PDF Content is blocked after successful deploy to Salesforce

### ISSUE THREAD

**Issue by LMPfeiffer** [svierk/awesome-lwc-collection#66]
Thanks for your effort! The PDF viewer in its simplicity is awesome!
However, I have the same issue as user: "ojedawinder" on Aug.11 wrote in the Stackexchange post (https://salesforce.stackexchange.com/questions/331123/convert-base64-to-pdf-and-display-it-in-lwc):
After successful deploy and integration on a Salesforce page I get a "content is blocked" message. Tried with Chrome and Edge, probably not a browser thing but rather settings.

In german:
Dieser Inhalt ist blockiert. Setze dich mit dem Websiteinhaber in Verbindung, um das Problem zu beheben.

Do you have an idea?
Best regards,
Lukas

**Comment by svierk** [comment]
Hi Lukas,
thanks for reporting the issue, it seems like with one of the recent releases the solution does not work anymore. I will investigate and post an update on the resolution.

Best regards
Sebastiano

**Comment by LMPfeiffer** [comment]
Hi Sebastiano,

thanks for your quick reply. The error message changed for me, but now "website" content can't be retrieved:
Tried with my own base64 encoded pdf and yours, tried in Edge, Firefox and Chrome. 
Hosted my LWC folder on my PC and on a network drive. Allowed in CSP Trusted Sites frame-src individually and all options. Deployed successfully to my org.

![grafik](https://github.com/svierk/awesome-lwc-collection/assets/143649542/2a843d2e-94b3-44e0-8e61-601732e2fcb9)

![grafik](https://github.com/svierk/awesome-lwc-collection/assets/143649542/646d9dc7-17c1-4562-b8d9-8116b2b06a19)

![grafik](https://github.com/svierk/awesome-lwc-collection/assets/143649542/320a09de-03eb-46dd-be84-01febb5a3090)

Do you have any idea what might be different in your setup?

Best regards,
Lukas

**Comment by svierk** [comment]
@LMPfeiffer as the download also worked for you and you are now simply facing iframe display issues, maybe also check if there are other browser settings, plugins etc. that might influence that. I will close the issue as the functionality of the LWC itself is given from my point of view. If you see something that needs to be changed in the implementation, please let me know.

**Comment by LMPfeiffer** [comment]
@svierk : Closing accepted, as it's obviously a browser config issue. I was able to make it visible at least in Firefox, Chrome "bug" reason still unknown. Thank's for your efforts!
![image](https://github.com/svierk/awesome-lwc-collection/assets/143649542/0f9df806-43ab-4be5-b6c2-f37b9a5a1556)

**Comment by ojedawinder** [comment]
Thank for your help @svierk
