### ISSUE TITLE
Running into errors when trying to deploy to staging

### ISSUE THREAD

**Issue by MWCalgae** [svierk/awesome-lwc-collection#81]
I know almost nothing, so forgive me if this is the wrong way of going about this. I am following the instructions of deploying this to staging after cloning it to a local repo and authorizing the org and this error is showing up:

Component Failures [4]
===============================================================================================================================
| Type  Name                   Problem                                                                                          
| ───── ────────────────────── ──────────────────────────────────────────────────────────────────────────────────────────────── 
| Error Account.Test_Field_Set In field: NumberofLocations__c - no CustomField named Account.NumberofLocations__c found (16:26) 
| Error customSlider           No TOKEN named force:base.spacingNone found                                                      
| Error Account.Test_Field_Set In field: NumberofLocations__c - no CustomField named Account.NumberofLocations__c found         
| Error customSlider           No TOKEN named force:base.spacingNone found  

Any ideas on how to proceed?

**Comment by svierk** [comment]
Hi @MWCalgae, thank you for pointing out these issues. There were indeed issues, which I have now resolved with the latest commits. The following has been fixed:

1. The FieldSet (Account.Test_Field_Set) included in the repo for the Custom Datatable LWC accidentally contained a Custom Field (NumberofLocations__c) that is not available by default in a normal Salesforce Org. I have therefore removed it.
2. The CSS file for the Custom Slider LWC used a no longer supported design token (spacingNone) which I therefore removed.

Please try again after you have pulled the latest changes and let me know if something still does not work with the deployment.
